# Generated by Django 4.2 on 2024-10-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_remove_examen_consulta_remove_resultado_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('tipoEstado', models.CharField(max_length=50, verbose_name='Tipo de estado')),
            ],
            options={
                'verbose_name_plural': 'Tipo de estado',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Examen')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha entrega')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examen.estado', verbose_name='Estado del Resultado')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examen.examen', verbose_name='Examen')),
            ],
        ),
    ]
