# Generated by Django 5.1.3 on 2024-11-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código'),
        ),
    ]
