# Generated by Django 4.2 on 2024-10-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cita', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('Hora_cita', models.DateTimeField(verbose_name='Hora')),
                ('Dia_cita', models.CharField(max_length=20, verbose_name='Día')),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('diagnostico', models.CharField(blank=True, max_length=100, null=True)),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.cita', verbose_name='Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('tipoEstado', models.CharField(max_length=50, verbose_name='Tipo de estado')),
            ],
            options={
                'verbose_name_plural': 'Tipo de estado',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Examen')),
                ('fechaEntrega', models.DateField(verbose_name='Fecha entrega')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, unique=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name_plural': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estado', verbose_name='Estado del Resultado')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.examen', verbose_name='Examen')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('primerApellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundoApellido', models.CharField(max_length=50, verbose_name='Segundo Apellido')),
                ('telefono', models.CharField(max_length=50, unique=True, verbose_name='Teléfono')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Medico',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='Medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.medico', verbose_name='Medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.paciente', verbose_name='Paciente'),
        ),
    ]
