# Generated by Django 5.0.6 on 2024-11-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_examen_consulta_remove_resultado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
