# Generated by Django 5.1.3 on 2024-11-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_paciente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='codigo_cita',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código'),
        ),
    ]
