# Generated by Django 5.0.6 on 2024-11-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_alter_cita_codigo_cita_alter_consulta_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='Dia_cita',
        ),
    ]
